#define Dynamic_Help_Window 1
#define Manage_Window_Layouts_Dialog 10
#define Manage_Windows_Dialog 11
#define Messages_Window 12
#define New_Updates_Available_Dialog 13
#define Required_Windows_Components_Dialog 14
#define MadCap_Pulse_Configuration_Wizard 15
#define Crash 16
#define Select_SQL_Server_and_Database_Dialog 17
