#define Manage_Window_Layouts_Dialog 10
#define Manage_Windows_Dialog 11
#define Messages_Window 12
#define New_Updates_Available_Dialog 13
#define Options_Dialog_General_Tab 14
#define Welcome 17
#define Select_UI_Language_Dialog 23
#define Crash 24
#define Start_Page 25
